name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install gtest
      run: sudo apt-get install libgtest-dev
    - name: install cmake
      run: sudo apt-get install cmake 
    - name: compile gtest
      working-directory: /usr/src/gtest
      run: sudo cmake CMakeLists.txt
    - name: run make on gtest  
      working-directory: /usr/src/gtest
      run: sudo make 
    - name: copy gtest lib files 
      working-directory: /usr/src/gtest/lib
      run: sudo cp *.a /usr/lib
    - name: Run cmake on project
      run: mkdir build && cd build && cmake .. && make
    - name: run tests
      run: cd build && ctest


    - name: install lcov
      run: sudo apt-get install lcov
    - name: create coverage folder
      run: mkdir coverage
    - name: generate cov executable
      run: g++ -o coverage/cov -fprofile-arcs -ftest-coverage tests/EasyMath.cpp -lgtest -lpthread -Ilib
    - name: run coverage executable
      run: ./coverage/cov
   
    - name: tree
      run: ls && ls .. && ls ...
    
    - name: create folders
      run: cd coverage && mkdir reports && cd reports
    - name: run gcov
      run: gcov ../../tests/EasyMath.cpp -o ../cov-EasyMath.gc
    - name: run lcov
      run: lcov -d .. -c --directory . --output-file coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/reports/
        fail_ci_if_error: true
        # files: ./coverage1.xml,./coverage2.xml
        # flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
        

      

